[book]
authors = ["wabinab"]
language = "en"
multilingual = false
src = "src"
title = "Xenoblade Chronicles 3"
description = "Xenoblade Chronicles 3 the movie put into words."

[preprocessor.footnote]